version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_ws
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./mime.types:/etc/nginx/mime.types
      - ./website:/usr/share/nginx/html
      - /etc/letsencrypt/live/onmyown.pp.ua/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/onmyown.pp.ua/privkey.pem:/etc/nginx/privkey.pem
    restart: always
